# Generated by Django 5.1.7 on 2025-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('correct', models.CharField(max_length=200)),
                ('wrong1', models.CharField(max_length=200)),
                ('wrong2', models.CharField(max_length=200)),
                ('wrong3', models.CharField(max_length=200)),
                ('fan', models.ManyToManyField(to='student.fan')),
            ],
        ),
    ]
