# Generated by Django 5.1.7 on 2025-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kursi', models.ManyToManyField(to='student.kursi')),
                ('shakli', models.ManyToManyField(to='student.shakli')),
                ('turi', models.ManyToManyField(to='student.turi')),
                ('yunalish', models.ManyToManyField(to='student.yunalish')),
            ],
        ),
    ]
