# Generated by Django 5.1.7 on 2025-03-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='correct',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='question',
            field=models.TextField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='wrong1',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='wrong2',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='wrong3',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
    ]
