# Generated by Django 4.2.20 on 2025-04-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_yourmodel_age_remove_yourmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='fan',
            field=models.ManyToManyField(to='student.fan'),
        ),
    ]
