# Generated by Django 4.2.20 on 2025-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_yourmodel_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='smestr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guruh',
            name='fan',
            field=models.ManyToManyField(to='student.fan'),
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
