# Generated by Django 5.2 on 2025-04-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_fan_smestr_guruh_fan_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('kurs', models.IntegerField()),
                ('guruh', models.CharField(max_length=50)),
                ('yonalish', models.CharField(max_length=100)),
                ('togri_soni', models.IntegerField()),
                ('umumiy_savollar', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.fan')),
            ],
        ),
    ]
