# Generated by Django 5.2 on 2025-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_natija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natija',
            name='kurs',
            field=models.CharField(max_length=50),
        ),
    ]
