# Generated by Django 4.2.20 on 2025-04-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_natija_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natija',
            name='familiya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='natija',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.fan'),
        ),
        migrations.AlterField(
            model_name='natija',
            name='guruh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='natija',
            name='ism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='natija',
            name='kurs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='natija',
            name='yonalish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
